### ISSUE TITLE
max LEDS_COUNT is 256

### ISSUE THREAD

**Issue by ovolkov** [Freenove/Freenove_WS2812_Lib_for_ESP32#1]
Hello! You can add support for more 256 Leds count?

**Comment by Zhentao-Lin** [comment]
OK, we've updated the code on GitHub. Now it can support more than 256 LEDs. Theoretically it can support 65,536 LEDs, but in fact, the ESP32 does not have enough memory, so it can only support about 42,100 LEDs. If your code has anything else, the number of LEDs it can support will be even lower. But it's a lot more than the original, isn't it?

**Comment by ovolkov** [comment]
Thank you! That's enough for now.
