### ISSUE TITLE
Libary can not be compiled

### ISSUE THREAD

**Issue by tkkg01** [Freenove/Freenove_WS2812_Lib_for_ESP32#11]
Hey there, i want to use this libay.
Since yesterdy it worked very well.
Today I got this error while using the Rainbow example.

Are you able to help me?

\libraries\Freenove_WS2812_Lib_for_ESP32\src/Freenove_WS2812_Lib_for_ESP32.h:61:9: error: 'rmt_obj_t' does not name a type
   61 |         rmt_obj_t* rmt_send = NULL;
      |         ^~~~~~~~~

exit status 1

Compilation error: exit status 1

**Comment by Zhentao-Lin** [comment]
arduino-esp32 version 3.0.x has changed the underlying driver related to rmt, so it cannot be used, please return the version to version 2.0.x

**Comment by tkkg01** [comment]
Ah thanks 
works now

**Comment by Zhentao-Lin** [comment]
It has been updated to version 2.0.0 and supports Arduino-ESP32 version 3.0.x.
If your Arduino-ESP32 version is 2.0.x, continue to use the 1.0.5 version of the library.
