### ISSUE TITLE
error = "rmt_obj_t" does not name a type ? = incompatible with Freenove_WS2812_Lib_for_ESP32

### ISSUE THREAD

**Issue by DavidRHerbert** [Freenove/Freenove_WS2812_Lib_for_ESP32#13]
Arduino IDE 2.3.2 with ESP32S3 Dev Module running Sketch_02_WS2812.ino Example lib dated 22/02/2023

Trying to run supplied example code and will not verify. 

GPT = The error you're encountering, 'rmt_obj_t' does not name a type, suggests that the Freenove_WS2812_Lib_for_ESP32 library might be incompatible with the version of the ESP32 core or the Arduino IDE you are using. This issue is likely related to the use of RMT (Remote Control) functionality in the library, which may have changed or been deprecated in recent versions.

Note FastLED library also will not work. ? due to changes in the ESP32 RMT (Remote Control) peripheral definitions in the newer versions of the ESP32 Arduino core ?

**Comment by Zhentao-Lin** [comment]
If your Arduino-ESP32 version is 3.0.x, re-download the latest version 2.0.0.
If your Arduino-ESP32 version is 2.0.x, use the Light Library version 1.0.5

**Comment by DavidRHerbert** [comment]
Fixed 
1) Use Freenove_WS2812_Lib_for_ESP32-2.0.0.zip
2) in code change data type from unsigned int "u8" to just "Int"

**Comment by Zhentao-Lin** [comment]
Yes, the definition like u8 is not very normative, so after I think about it, I still plan to remove it.  You can use uint8_t instead of u8.
