### ISSUE TITLE
This library not working to platformio

### ISSUE THREAD

**Issue by vishwajit-upswing** [Freenove/Freenove_WS2812_Lib_for_ESP32#14]
At compile time, an error occurs in the library because of a recent change: 'rmt_mem = RMT_MEM_NUM_BLOCKS_1;'.

**Comment by Zhentao-Lin** [comment]
I haven't tried it on platformio, I've only tried it on Arduino ESP32 3.0.x. If your Arduino ESP32 version is 2.0.x, download the previous version. The latest version no longer supports 2.0.x
