### ISSUE TITLE
working again with last Arduino core ? 

### ISSUE THREAD

**Issue by phil31** [Freenove/Freenove_WS2812_Lib_for_ESP32#2]
hi,

i'm testing the RGBW sketch and i have a strange flickers/random colors !
Rainbow test code seem strange  too !

using pin 5 on my ESP32-WROOM-32UE board.
core 2.0.0, a lot of compilation complain and all leds are white !
core 1.0.6 a lot of flicker .

please anybody can confirm that it will work right on pin 5 ? with RMT feature ?

thanks, regards

**Comment by Zhentao-Lin** [comment]
Esp32-wroom module chip is D0WQ series. Arduino kernel version 2.0.0 is suitable for module chip S2 and C3 series.  So don't choose an Arduino kernel greater than 1.0.6.  
Before you can use https://dl.espressif.com/dl/package_esp32_index.json instead of URLs.  
I have tested that Pin5 works normally.

**Comment by phil31** [comment]
hi, thanks for your reply, but i don't think that core 2.0 is not compatible with D0WQ dual cpu parts ! ?
the 2.0 add support for S2 & C3 series
look at this link : [https://docs.espressif.com/projects/arduino-esp32/en/latest/getting_started.html#supported-soc-s](https://docs.espressif.com/projects/arduino-esp32/en/latest/getting_started.html#supported-soc-s)


it seem that core 2.0 modify things about internal RMT module ..?

regards

**Comment by Zhentao-Lin** [comment]
D0WQ has 8 RMT channels, S2 has 4 and C3 has 2. I guess there are some differences between 2.0.0 kernel and 1.0.6.  I didn't have kernel 2.0.0 when I wrote this library, so I don't yet know what caused the compile failure.  I think after I finish my work these days, I will take some time to solve this problem.  Thank you.

**Comment by phil31** [comment]
i test others libs (FastLED.. ), where we can select which RMT channel we want, it's not better !

thanks if you can have a look, regards
