### ISSUE TITLE
Variable cpu frequency

### ISSUE THREAD

**Issue by catalinbalteanu** [Freenove/Freenove_WS2812_Lib_for_ESP32#6]
The library breaks when changing the cpu frequency using **setCpuFrequencyMhz** is there a way to change the clock source so that it works even when the cpu frequency is not the same as it was when initiated?

**Comment by Zhentao-Lin** [comment]
I'm afraid we can't do that.

**Comment by Zhentao-Lin** [comment]
I'm sorry we can't do that.
